#!/bin/bash

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Use Hub
alias git=hub

# Jobs
alias j=jobs

# Vim
alias m="mvim"
alias v="mvim -v"
alias vim="mvim -v"

# Django
alias pym="python manage.py"
alias pymrs="python manage.py runserver"
alias pymrs+="python manage.py runserver_plus"
alias pyms="python manage.py shell"
alias pyms+="python manage.py shell_plus"

# Re-attach or start new Screen
alias scr="screen -R"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# Solr
alias solr="/usr/local/bin/solr $SOLR_CONF"

