brew install "awscli"
brew install "b2-tools"
brew install "bash"
brew install "bash-completion@2"
brew install "bat"
brew install "bitwarden-cli"
brew install "colima"
brew install "cowsay"
brew install "ctags"
brew install "direnv"
brew install "dive"
brew install "exiftool"
brew install "fd"
brew install "ffind"
brew install "fish"
brew install "fnm"
brew install "fzf"
brew install "gawk"
brew install "gh"
brew install "gist"
brew install "git"
brew install "git-standup"
brew install "gnu-typist"
brew install "gnupg"
brew install "hadolint"
brew install "htop"
brew install "iftop"
brew install "jpegoptim"
brew install "jq"
brew install "just"
brew install "markdown"
brew install "mas"
brew install "moreutils"
brew install "msmtp"
brew install "neomutt"
brew install "neovim"
brew install "nmap"
brew install "offlineimap"
brew install "optipng"
brew install "pgcli"
brew install "pinentry-mac"
brew install "pipx"
brew install "pv"
brew install "pyenv"
brew install "python-yq"
brew install "reattach-to-user-namespace"
brew install "redis"
brew install "ripgrep"
brew install "rsync"
brew install "sd"
brew install "shellcheck"
brew install "starship"
brew install "teensy_loader_cli"
brew install "tig"
brew install "tldr"
brew install "tmux"
brew install "tree"
brew install "urlview"
brew install "w3m"
brew install "watch"
brew install "watchman"
brew install "wget"
brew install "xz"
brew install "yarn"
brew install "yt-dlp"
brew install "ghickman/banking-tools/banking-tools", args: ["HEAD"]
brew install "heroku/brew/heroku"
brew install "jawshooah/pyenv/pyenv-default-packages", args: ["HEAD"]
brew install "keith/formulae/contacts-cli"
brew install "nvie/tap/git-toolbelt"
brew services start offlineimap
brew services start redis
brew install --cask "1password"
brew install --cask "1password-cli"
brew install --cask "adobe-acrobat-reader"
brew install --cask "alfred"
brew install --cask "appcleaner"
brew install --cask "around"
brew install --cask "backblaze"
brew install --cask "battle-net"
brew install --cask "bitwarden"
brew install --cask "camo-studio"
brew install --cask "cloudapp"
brew install --cask "daisydisk"
brew install --cask "dash"
brew install --cask "discord"
brew install --cask "docker"
brew install --cask "doxie"
brew install --cask "drawio"
brew install --cask "elgato-control-center"
brew install --cask "fantastical"
brew install --cask "figma"
brew install --cask "firefox"
brew install --cask "font-inconsolata-for-powerline"
brew install --cask "garagesale"
brew install --cask "gemini"
brew install --cask "google-chrome"
brew install --cask "graphiql"
brew install --cask "handbrake"
brew install --cask "hazel"
brew install --cask "highsierramediakeyenabler"
brew install --cask "iterm2"
brew install --cask "karabiner-elements"
brew install --cask "lastfm"
brew install --cask "logitech-g-hub"
brew install --cask "maestral"
brew install --cask "medis"
brew install --cask "mic-drop"
brew install --cask "minecraft"
brew install --cask "miro"
brew install --cask "multipass"
brew install --cask "netspot"
brew install --cask "ngrok"
brew install --cask "numi"
brew install --cask "nvidia-geforce-now"
brew install --cask "obsidian"
brew install --cask "omnifocus"
brew install --cask "pixelstick"
brew install --cask "postgres"
brew install --cask "postico"
brew install --cask "raspberry-pi-imager"
brew install --cask "signal"
brew install --cask "sketch"
brew install --cask "sketchup"
brew install --cask "slack"
brew install --cask "sonos"
brew install --cask "soundsource"
brew install --cask "spotify"
brew install --cask "spotify-notifications"
brew install --cask "starcraft"
brew install --cask "stats"
brew install --cask "steam"
brew install --cask "superduper"
brew install --cask "synology-drive"
brew install --cask "syntax-highlight"
brew install --cask "tableplus"
brew install --cask "teensy"
brew install --cask "the-unarchiver"
brew install --cask "tor-browser"
brew install --cask "trackerzapper"
brew install --cask "unrarx"
brew install --cask "viscosity"
brew install --cask "vlc"
brew install --cask "vmware-fusion"
brew install --cask "whalebird"
brew install --cask "whatsapp"
brew install --cask "wireshark"
brew install --cask "zoom"
# mas "Blinks", id: 998804308
# mas "Disk Speed Test", id: 425264550
# mas "Keynote", id: 409183694
# mas "Mastonaut", id: 1450757574
# mas "Microsoft Word", id: 462054704
# mas "Moom", id: 419330170
# mas "Numbers", id: 409203825
# mas "Pages", id: 409201541
# mas "Shush", id: 496437906
# mas "Textual IRC Client", id: 1262957439
# mas "ToothFairy", id: 1191449274
# mas "Tweetbot", id: 1384080005
# mas "Xcode", id: 497799835
