tap 'caskroom/cask'
tap 'ghickman/banking-tools', 'https://github.com/ghickman/banking-tools.git'
tap 'neomutt/neomutt'
tap 'neovim/neovim'

brew 'ack'
brew 'asciinema'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'contacts'
brew 'cowsay'
brew 'ctags'
brew 'diff-so-fancy'
brew 'direnv'
brew 'exiftool'
brew 'ffind'
brew 'ffmpeg'
brew 'gawk'
brew 'ghickman/banking-tools/banking-tools', args: ['HEAD']
brew 'gist'
brew 'git'
brew 'git-extras'
brew 'gnu-typist'
brew 'gnupg'
brew 'gnupg2'
brew 'gpg-agent'
brew 'gpgme'
brew 'heroku'
brew 'htop'
brew 'hub'
brew 'jhead'
brew 'jpeg'
brew 'jq'
brew 'keybase'
brew 'lftp'
brew 'libyaml'
brew 'markdown'
brew 'mas'
brew 'mobile-shell'
brew 'moreutils'
brew 'msmtp'
brew 'mtr'
brew 'namebench'
brew 'neomutt/neomutt/neomutt', args: ['with-gpgme', 'with-notmuch-patch', 'with-sidebar-patch']
brew 'neovim/neovim/neovim'
brew 'nmap'
brew 'node'
brew 'notmuch'
brew 'offlineimap'
brew 'pinentry-mac'
brew 'pyenv'
brew 'readline'
brew 'redis'
brew 'ruby'
brew 'selecta'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'teensy_loader_cli'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'typespeed'
brew 'urlview'
brew 'w3m'
brew 'watch'
brew 'wget'
brew 'youtube-dl'

cask 'alfred'
cask 'appcleaner'
cask 'arq'
cask 'bartender'
cask 'cloak'
cask 'daisydisk'
cask 'dash'
cask 'dropbox'
cask 'eye-fi'
cask 'firefox'
cask 'flux'
cask 'garagesale'
cask 'google-chrome'
cask 'gpgtools'
cask 'handbrake'
cask 'hazel'
cask 'iterm2'
cask 'karabiner'
cask 'lastfm'
cask 'licecap'
cask 'medis'
cask 'minecraft'
cask 'ngrok'
cask 'pixelstick'
cask 'postgres'
cask 'postico'
cask 'screenhero'
cask 'sketch'
cask 'sketchup'
cask 'slack'
cask 'spotify'
cask 'spotify-notifications'
cask 'steam'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'viscosity'
cask 'vlc'
cask 'whatsapp'
cask 'wireshark'
cask 'xbench'

mas '1Password', id: 443987910
mas 'CloudApp', id: 417602904
mas 'Keynote', id: 409183694
mas 'Moom', id: 419330170
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Shush', id: 496437906
mas 'Textual', id: 896450579
mas 'Tweetbot', id: 557168941
mas 'Xcode', id: 497799835
