#!/bin/bash

brew tap caskroom/cask
brew install brew-cask

brew cask install alfred
brew cask install appcleaner
brew cask install arq
brew cask install colorschemer-studio
brew cask install cloak
brew cask install daisydisk
brew cask install dropbox
brew cask install evernote
brew cask install flux
brew cask install firefox
brew cask install gpgtools
brew cask install handbrake
brew cask install inc
brew cask install iterm2
brew cask install karabiner
brew cask install lastfm
brew cask install licecap
brew cask install limechat
brew cask install mactracker
brew cask install minecraft
brew cask install mumble
brew cask install pixelstick
brew cask install sequel-pro
brew cask install screenhero
brew cask install slack
brew cask install sketchup
brew cask install skype
brew cask install spotify
brew cask install sqwiggle
brew cask install steam
brew cask install the-unarchiver
brew cask install unrarx
brew cask install utorrent
brew cask install vimr
brew cask install vlc

brew cask alfred link
