#!/bin/bash

# Basics
brew install awscli
brew install bash
brew install bash-completion
brew install cowsay
brew install gist
brew install mobile-shell
brew install mtr
brew install namebench
brew install nmap
brew install watch
brew install wget
brew install youtube-dl

# Git
brew install git
brew install git-extras
brew install hub

# Vim
brew install ctags
brew install macvim

# Search
brew install ack
brew install ffind
brew install gawk
brew install pt
brew install selecta
brew install the_silver_searcher

# Mutt
brew install contacts
brew install msmtp
brew install notmuch
brew install offline-imap
brew install sqlite
brew install tokyo-cabinet
brew install urlview
brew install w3m

# Dev
brew install direnv
brew install libmemcached
brew install markdown
brew install reattach-to-user-namespace
brew install redis
brew install solr
brew install tmux

# Python
brew install python
brew install python3
brew install pypy
brew install pyenv

# Typing
brew install gnu-typist
brew install typespeed

# Organising Photos/Videos
brew install exiftool
brew install jhead

# Crypto
brew install gnupg
brew install gnupg2
brew install keybase
