#!/bin/bash

if [ x`which brew` != x ]; then
    if [ -f `brew --prefix`/etc/bash_completion ]; then
      . `brew --prefix`/etc/bash_completion
    fi
fi

BLACK="\[\033[0;30m\]"
GREEN="\[\033[0;32m\]"
RED="\[\033[0;31m\]"
WHITE="\[\033[0;37m\]"
YELLOW="\[\033[0;33m\]"

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1

TIME="$RED\[\$(date +%H:%M:%S)\]"

PS1="$TIME $GREEN\h $BLACK\W$YELLOW\$(__git_ps1)$BLACK\n$ "
