[aws]
disabled = true

[cmd_duration]
style = "bold red"

[gcloud]
disabled = true

[git_status]
deleted = ""
modified = "*"
untracked = ""

[jobs]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
style = "bold green"
