defaults:
  extension:
    - .avi
    - .mkv
    - .mp4
    - .webm
  format: '%n - %sx%e - %t%x'
  ignore:
    - .DS_Store
    - thumbs.db
  organise: yes
  renamed: /Volumes/Media/TV/
  specials_folder: Specials

'24':
  format: '%n - %s%e'

avengers assemble:
  canonical: Avengers Assemble (2013)

american dad:
  canonical: American Dad!

archer 2009:
  canonical: Archer (2009)

castle 2009:
  canonical: Castle (2009)

doctor who 2005:
  canonical: Doctor Who (2005)

'marvels agents of s h i e l d':
  canonical: "Marvel's Agents of S.H.I.E.L.D."

"marvel's agents of s h i e l d":
  canonical: "Marvel's Agents of S.H.I.E.L.D."

"marvel's avengers assemble":
  canonical: 'avengers assemble (2013)'

ntsf sd suv:
  canonical: 'NTSF:SD:SUV::'

'the newsroom 2012':
  canonical: The Newsroom (2012)
