#!/bin/sh

set -e

git ls-files | \
    ctags \
    -L - \
    -f tags \
    --language-force=python \
    --python-kinds=-ivm \
    --exclude=.tox \
    --exclude=.direnv \
    --exclude=bower_components \
    --exclude=node_modules \
    --exclude=README.*
