#!/bin/bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."

# Jobs
alias j=jobs

# Vim
alias m="open -a VimR.app"
alias vim="nvim"
alias v="vim"

# Django
alias pym="python manage.py"
alias pymrs="python manage.py runserver"
alias pymrs+="python manage.py runserver_plus"
alias pyms="python manage.py shell"
alias pyms+="python manage.py shell_plus"

# Heroku
alias hpym="heroku run python manage.py"

# Re-attach or start new Screen
alias scr="screen -R"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# Solr
alias solr="/usr/local/bin/solr $SOLR_CONF"

# Mutt
alias e="cd ~/Desktop && mutt"
alias ffs="ps aux | grep offlineimap | grep -v grep | awk '{print $2}' | xargs kill -9"

if hash brew 2>/dev/null; then
    alias cask="brew cask"
fi

# Project Directories
alias c="cd /Volumes/Media/Downloads/complete/"
alias g="cd ~/Projects/gitprime/gitprime"
alias t="cd ~/Projects/tvr"

# Fileserver
alias fs="ssh fs"

# Get first directory from path in previous commands final token
alias lbb="echo !$ | awk -F "/" '{print $1}'"

# Serve a directory
alias serve="python -m http.server"

# speed up direnv usage
alias da="direnv allow"

# ffs
alias p8="ping 8.8.8.8"
