#!/bin/bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."

# Jobs
alias j=jobs

# Vim
alias m="open -a VimR.app"
alias vim="nvim"
alias v="vim"

# Django
alias pym="python manage.py"
alias pymrs="python manage.py runserver"
alias pymrs+="python manage.py runserver_plus"
alias pyms="python manage.py shell"
alias pyms+="python manage.py shell_plus"

# Heroku
alias hpym="heroku run python manage.py"

# Re-attach or start new Screen
alias scr="screen -R"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# Mutt
alias e="cd ~/Desktop && neomutt"
alias ffs="ps aux | grep offlineimap | grep -v grep | awk '{print $2}' | xargs kill -9"

if hash brew 2>/dev/null; then
    alias cask="brew cask"
fi

# Project Directories
alias c="cd /Volumes/Media/Downloads/complete/"
alias gcs="cd ~/Projects/gitprime/grand-central"
alias gp="cd ~/Projects/gitprime/gitprime"
alias t="cd ~/Projects/tvr"

# Fileserver
alias fs="ssh fs"

# Get first directory from path in previous commands final token
alias lbb="echo !$ | awk -F \"/\" '{print $1}'"

# Serve a directory
alias serve="python -m http.server"

# speed up direnv usage
alias da="direnv allow"

# ffs
alias p8="ping 8.8.8.8"

# Work
alias start-the-day="git fetch origin +master:master +production:production +canary:canary && git stash -u && git checkout master && pip-sync dev-requirements.txt requirements.txt && yarn && pym migrate && git fetch --prune && git sb"

# brew
alias b="brew update && brew upgrade && brew cleanup"
