#!/bin/bash

# Jobs
alias j=jobs

# Vim
alias vim="nvim"
alias v="vim"

# Django
alias pym="python manage.py"
alias pymrs="python manage.py runserver"
alias pymrs+="python manage.py runserver_plus"
alias pyms="python manage.py shell"
alias pyms+="python manage.py shell_plus"

# Re-attach or start new Screen
alias scr="screen -R"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# Mutt
alias e='cd ${HOME}/Desktop && neomutt'
alias ffs="pkill -9 -f offlineimap.py"

if hash brew 2>/dev/null; then
    alias cask="brew cask"
fi

# Project Directories
alias t='cd ${HOME}/Projects/tvr'

# speed up direnv usage
alias da="direnv allow"

# ffs
alias p1="ping 192.168.0.1"
alias p2="ping 192.168.10.1"
alias p8="ping 8.8.8.8"

# brew
alias b="brew update && brew upgrade && brew cleanup"

# work
alias th='cd ${HOME}/Projects/treeherder'
