#!/bin/bash

function run_at_repo_top_level {
    start=`pwd`
    top_level=`/usr/local/bin/git rev-parse --show-toplevel`
    pip install -r $top_level/$1
}

function pipr {
    run_at_repo_top_level "requirements.txt"
}

function pipd {
    run_at_repo_top_level "dev_requirements.txt"
}

function man() {
    open dash://man:$1
}

function take() {
    mkdir -p "$1"
    cd "$1"
}
