#!/bin/sh

if hash brew 2>/dev/null; then
    export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
    bash_completion_path="$(brew --prefix)/etc/profile.d/bash_completion.sh"
    if [ -r "$bash_completion_path" ]; then
        # shellcheck disable=SC1090
        . "$bash_completion_path"
    fi
fi

GREEN="\[\033[38;5;120m\]"
PINK="\[\033[38;5;183m\]"
WHITE="\[\033[38;5;231m\]"
YELLOW="\[\033[38;5;228m\]"

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1

TIME="\\[\$(date +%H:%M:%S)\\]"

PS1="$GREEN$TIME $PINK\\h $WHITE\\W$YELLOW\$(__git_ps1)$WHITE\\n$ "
