#!/bin/sh

if hash brew 2>/dev/null; then
    bash_completion_path="$(brew --prefix)/etc/profile.d/bash_completion.sh"
    if [ -r "$bash_completion_path" ]; then
        # shellcheck disable=SC1090
        . "$bash_completion_path"
    fi

    git_prompt_path="$(brew --prefix)/etc/bash_completion.d/git-prompt.sh"
    if [ -r "$git_prompt_path" ]; then
        # shellcheck disable=SC1090
        . "$git_prompt_path"
    fi
fi

GREEN="\\[\\033[0;32m\\]"
RED="\\[\\033[0;31m\\]"
WHITE="\\[\\033[0;37m\\]"
YELLOW="\\[\\033[0;33m\\]"

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1

TIME="\\[\$(date +%H:%M:%S)\\]"

PS1="$RED$TIME $GREEN\\h $WHITE\\W$YELLOW\$(__git_ps1)$WHITE\\n$ "
