#!/bin/bash

# Path
# base
export PATH="$HOME/.bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

# git toolbelt
if [ -d "$HOME/.files/git-toolbelt" ]; then
    export PATH="$HOME/.files/git-toolbelt:$PATH"
fi

# postgres
if [ -d "/Applications/Postgres.app" ]; then
    export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
fi

# Heroku Toolbelt
heroku="/usr/local/heroku/bin"
if [ -d "$heroku" ]; then
    export PATH="$heroku:$PATH"
fi

# Vim as Default Editor
export EDITOR="/usr/local/bin/nvim"

# Colours
export CLICOLOR=1

# force the use of correct arch flags
export ARCHFLAGS="-arch x86_64"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Save commands to history immediately after they are run.
export PROMPT_COMMAND="history -a"

# Append to the history file, don't overwrite it
shopt -s histappend

# Don't put duplicate lines in the history, see bash(1) for more options.
export HISTCONTROL=ignoredups:ignorespace

# Larger bash history (allow 32³ entries; default is 500)
export HISTFILESIZE=$HISTSIZE
export HISTIGNORE="ls:fg:e:v"
export HISTSIZE=32768
export HISTTIMEFORMAT="%F %T "

# No pycs
export PYTHONDONTWRITEBYTECODE=1

# brew
export HOMEBREW_NO_AUTO_UPDATE=1

# FZF
export FZF_DEFAULT_COMMAND="ag -g \"\""

# No really, no fucking cows
export ANSIBLE_NOCOWS=1


# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# configure direnv to work with NVM
export NODE_VERSIONS="$NVM_DIR/versions/node"
export NODE_VERSION_PREFIX="v"
