#!/bin/bash

# Path
# base
export PATH="$HOME/.bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

# git toolbelt
if [ -d "$HOME/.files/git-toolbelt" ]; then
    export PATH="$HOME/.files/git-toolbelt:$PATH"
fi

# postgres
if [ -d "/Applications/Postgres.app" ]; then
    export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
fi

if [ -d "$HOME/.pyenv" ]; then
    export PATH="$HOME/.pyenv/shims:$PATH"
fi

# Heroku Toolbelt
heroku="/usr/local/heroku/bin"
if [ -d "$heroku" ]; then
    export PATH="$heroku:$PATH"
fi

# Vim as Default Editor
export EDITOR="/usr/local/bin/nvim"

# Colours
export CLICOLOR=1
export LS_COLORS='di=01;34'
export DJANGO_COLORS="light"

# force the use of correct arch flags
export ARCHFLAGS="-arch x86_64"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Global Bash History
export PROMPT_COMMAND="history -a"

# Larger bash history (allow 32³ entries; default is 500)
export HISTCONTROL=ignoredups
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTTIMEFORMAT="%F %T "

# No pycs
export PYTHONDONTWRITEBYTECODE=1

export HOMEBREW_NO_AUTO_UPDATE=1
