#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT

files=`find . -path *migrations -prune -o -name "*.py"`
ctags \
    --exclude={.tox,.venv,tags,.git,.sass-cache,.lib} \
    --exclude={distribute,virtualenv}* \
    --exclude={*.pyc} \
    -f.git/tags.$$ \
    --language-force=python \
    --python-kinds=-ivm \
    $files

rm .git/tags.$$.bak
mv .git/tags.$$ tags
